/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yamary
 */
public class Computadoras extends javax.swing.JFrame {

    /**
     * Creates new form Computadoras
     */
    public Computadoras() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbComputadoras = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btbAtras = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Sistemas", "Quimica", "Industrial", "Mecanica", "Gestion", "Petrolera", "Electrica", "Electronica", "Administrativo", "Biblioteca" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 170, 40));

        TbComputadoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N. Inventario", "Estado", "N. Serie", "RAM", "ROM", "Procesador", "Marca"
            }
        ));
        jScrollPane1.setViewportView(TbComputadoras);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 190));

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1485476008-artboard-1_78539 (1).png"))); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Computadoras");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 280, 30));

        btbAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/1486485553-ago-arrow-arrow-left-back-previous-direction-left_81160.png"))); // NOI18N
        btbAtras.setText("Atras");
        btbAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(btbAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/fondo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btbAtrasMouseClicked

        Menu y =new Menu();
        y.setVisible(true);
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_btbAtrasMouseClicked

    
    public ArrayList<Equipo> equiposList(){
    ArrayList<Equipo> equiposList = new ArrayList<>();
    
        try  {
            conexion conex = new conexion();
            Connection conect = conex.Conexion();
            String q1 = "SELECT * FROM equipo WHERE dpto="+ String.valueOf(jComboBox1.getSelectedIndex()).trim();
            Statement st = conect.createStatement();
            ResultSet rs = st.executeQuery(q1);
            Equipo equipos;
            while(rs.next()){
                equipos = new Equipo(rs.getString("numinvent"), rs.getString("estado"), rs.getString("numserie"), rs.getString("ram"), rs.getString("rom"), rs.getString("procesador"),rs.getString("marca"), rs.getString("dpto"));
                equiposList.add(equipos);
            } 
        } catch (SQLException e) {
            //JOptionPane.showMessageDialog(null, "Error en la consulta es : " + e.getMessage());
        }
    return equiposList;
    }
    
    public void show_user (){
        ArrayList <Equipo> list = equiposList();
        DefaultTableModel model = (DefaultTableModel) TbComputadoras.getModel();
        model.setRowCount(0);
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            Object object = row[i];
            row[0] = list.get(i).getNuminvent();
            row[1] = list.get(i).getEstado();
            row[2] = list.get(i).getNumserie();
            row[3] = list.get(i).getRam();
            row[4] = list.get(i).getRom();
            row[5] = list.get(i).getProcesador();
            row[6] = list.get(i).getMarca();
            model.addRow(row);
        }
    }
    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        show_user();
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JTable TbComputadoras;
    private javax.swing.JButton btbAtras;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
